"""empty message

Revision ID: 086abc8f90dd
Revises: 590c383791a2
Create Date: 2024-02-07 12:38:05.588841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '086abc8f90dd'
down_revision = '590c383791a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_column('item_totalamount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_totalamount', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
