"""empty message

Revision ID: 12c106f74e80
Revises: 
Create Date: 2024-01-30 18:01:05.714935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c106f74e80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_username', sa.String(length=20), nullable=True),
    sa.Column('admin_pwd', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('categories',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fname', sa.String(length=100), nullable=False),
    sa.Column('user_lname', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_pix', sa.String(length=120), nullable=True),
    sa.Column('user_datereg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('budget',
    sa.Column('budget_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_userid', sa.Integer(), nullable=True),
    sa.Column('budget_name', sa.String(length=100), nullable=False),
    sa.Column('current_income', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('budget_id')
    )
    op.create_table('budget_item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_budgetid', sa.Integer(), nullable=True),
    sa.Column('item_catid', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_amount', sa.Float(), nullable=False),
    sa.Column('item_status', sa.Enum('1', '0'), nullable=False),
    sa.ForeignKeyConstraint(['item_budgetid'], ['budget.budget_id'], ),
    sa.ForeignKeyConstraint(['item_catid'], ['categories.cat_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('expense',
    sa.Column('expense_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_userid', sa.Integer(), nullable=True),
    sa.Column('expense_itemid', sa.Integer(), nullable=True),
    sa.Column('expense_amount', sa.Float(), nullable=False),
    sa.Column('expense_desc', sa.String(length=200), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_itemid'], ['budget_item.item_id'], ),
    sa.ForeignKeyConstraint(['expense_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    op.drop_table('budget_item')
    op.drop_table('budget')
    op.drop_table('user')
    op.drop_table('categories')
    op.drop_table('admin')
    # ### end Alembic commands ###
