"""empty message

Revision ID: 1ad99c8f8614
Revises: 12c106f74e80
Create Date: 2024-02-05 22:05:06.167848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ad99c8f8614'
down_revision = '12c106f74e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['budget_name'])

    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.alter_column('item_budgetid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('item_catid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.alter_column('item_catid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('item_budgetid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
