"""empty message

Revision ID: 3eeef3d6e0b7
Revises: 
Create Date: 2024-03-03 09:19:20.447194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3eeef3d6e0b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['admin_userid'], ['user_id'])

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('expense_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('expense_date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
