"""empty message

Revision ID: 590c383791a2
Revises: 1ad99c8f8614
Create Date: 2024-02-07 08:08:12.774931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590c383791a2'
down_revision = '1ad99c8f8614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_totalamount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_column('item_totalamount')

    # ### end Alembic commands ###
