"""empty message

Revision ID: 6bf5ab80c72b
Revises: 881658bd86f8
Create Date: 2024-02-10 21:57:17.762870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bf5ab80c72b'
down_revision = '881658bd86f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.alter_column('item_budgetid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.alter_column('item_budgetid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
