"""empty message

Revision ID: 7d0fe3214ed9
Revises: 408e4ecfeed3
Create Date: 2024-02-11 00:01:55.004912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0fe3214ed9'
down_revision = '408e4ecfeed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint('expense_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'budget_item', ['expense_itemid'], ['item_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('expense_ibfk_1', 'budget_item', ['expense_itemid'], ['item_id'])

    # ### end Alembic commands ###
