"""empty message

Revision ID: 837e2d3e2552
Revises: 0b23c29e3d7f
Create Date: 2024-03-04 21:33:36.798626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837e2d3e2552'
down_revision = '0b23c29e3d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index('budget_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index('budget_name', ['budget_name'], unique=True)

    # ### end Alembic commands ###
