"""empty message

Revision ID: 881658bd86f8
Revises: 086abc8f90dd
Create Date: 2024-02-10 21:52:15.988991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881658bd86f8'
down_revision = '086abc8f90dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_constraint('budget_item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'budget', ['item_budgetid'], ['budget_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('budget_item_ibfk_1', 'budget', ['item_budgetid'], ['budget_id'])

    # ### end Alembic commands ###
